Multiple algorithms for hole filling
vanvalenlab/deepcell-toolbox pull request #114
Opened 2021-08-13 23:29 UTC by ngreenwald

This PR closes #113. It adds in a fast option for hole-filling, and defaults to using this option for large images. For small images, the default remains the custom option, which is slightly more accurate for corner cases.

2021-08-16 18:59 UTC, ngreenwald commented
Your version is only slightly slower than Dave's but handles the corner cases, I don't think we need to have two options anymore since this is now only a small proportion of the processing time

2021-08-16 20:48 UTC, willgraf requested changes
I just commented in the issue as well, but I've updated the regionprops build a bit by using more intelligent properties. Can you please update this PR and re-request review?

2021-08-16 21:45 UTC, willgraf commented on deepcell_toolbox/utils.py
> +from skimage.measure import label, regionprops
Remove the unused imports

```suggestion
from skimage.measure import regionprops
from skimage.morphology import remove_small_holes
from skimage.segmentation import find_boundaries
```

2021-08-17 01:01 UTC, willgraf approved these changes

2021-08-17 01:03 UTC, merged

2021-08-18 17:50 UTC, oldridge commented
Thank you everyone for following up on this. I've been enjoying following the discussion, and I greatly appreciate your professionalism and efficiency in dealing with this issue. I can confirm this fix on my end as well, the new code works great!

2021-08-18 21:54 UTC, ngreenwald commented
Awesome, glad to hear it